### ISSUE TITLE
Data source for build order icons

### ISSUE THREAD

**Issue by jensbuehl** [CraftySalamander/RTS_Overlay#10]
Hi @CraftySalamander, I am a bit puzzled when it comes to adding additional icons in the overlay tool repository.
Which repository to pick? (I see the images in your RTS_Overlay as well as in Maguro's AoE4_Overlay).
I do not want to risk that the images get out of sync - so where should go what if I were to sync with aoe4guides and provide you with a pull request.

Thanks in advance!

**Comment by CraftySalamander** [comment]
Hi @jensbuehl 

On RTS Overlay, you can add them in [pictures/aoe4](https://github.com/CraftySalamander/RTS_Overlay/tree/master/pictures/aoe4).
For AoE4 Overlay, it is in [src/img/build_order](https://github.com/FluffyMaguro/AoE4_Overlay/tree/main/src/img/build_order).

I think the architecture is the same as in aoe4guides.
Adding images (or updating similar existing images) will not break anything (the overlays look in this folder to find which images are present each time you launch it).
But, it is better to not remove any image (so that old BOs remain compatible).

No code update is needed. Pushing new images is enough.

**Comment by jensbuehl** [comment]
Yeah, I though there is one data source and I have to change just one place. Will add 2 prs then.

Might be worth using a shared submodule (rts/aoe4 overlay) to have only one place to change. Otherwise, it will get out of sync easily. 

Thx for the Info.

**Comment by CraftySalamander** [comment]
It is merged. Thank you
