### ISSUE TITLE
Not showing up on windows

### ISSUE THREAD

**Issue by onixtsm** [CraftySalamander/RTS_Overlay#14]
The BO window shows in taskbar, but I cannot find it anywhere on the screen. I tried both versions - `.exe` and `.py`

**Comment by CraftySalamander** [comment]
Can you give me more details:
* Are you using more than 1 screen?
* What is the resolution of your screen(s)?
* Which version are you using (open version.json at the root of the folder)?
* Could you launch aoe2_overlay_with_console.exe (same for AoE4, SC2) and check what is written on the console or simply check what is written in your python console if you can launch the `.py`?
* In the settings file, what is the value of `upper_right_position` (initial position of the upper right corner)

**Comment by CraftySalamander** [comment]
Thanks for the report.
So, I assume your problem is solved. I will check if it is possible to add a check to prevent this upper right screen issue.

For the exe threat, I recently received many reports about similar issues, even from people using the overlay without issue before. I assume Windows defenders are more restrictive now.
