### ISSUE TITLE
Timer Feature Not Appearing AOE2

### ISSUE THREAD

**Issue by akakaz3311** [CraftySalamander/RTS_Overlay#23]
Ive seen demos where the timer can be activated to automatically change steps but that feature just doesnt seem to exist for me.  Ive added builds, evaluated time and of course get the time stamps to appear, but not the hotkey timer. Ive tried importing numerous builds with no luck. What am I missing?

**Comment by CraftySalamander** [comment]
Hi.
This feature is only present in the last release (1.9.1, check version.json at the root), but I assume you have it since you could evaluate the time.

When you paste your BO in the BO writer panel, does it indicate 'Valid build order (also for timing)?
Can you share your BO here?

` but not the hotkey timer` What do you mean? You do not see the button with the hourglass (will only appear for BOs with valid timing indications) or your timer hotkey is not working?
Usually, I only use the start BO timer with hotkey, and use buttons for the rest.
Does it work without hotkey?

**Comment by akakaz3311** [comment]
> Hi. This feature is only present in the last release (1.9.1, check version.json at the root), but I assume you have it since you could evaluate the time.
> Have 1.9.1

> When you paste your BO in the BO writer panel, does it indicate 'Valid build order (also for timing)? Can you share your BO here?
> Yes.  Ive tried with defaults, website, etc.  "Valid build order (also for timing)" is annotated.  Ive never seen an hourglass appear and hotkeys dont do anything because the manual timer has never appeared.

> ` but not the hotkey timer` What do you mean? You do not see the button with the hourglass (will only appear for BOs with valid timing indications) or your timer hotkey is not working? Usually, I only use the start BO timer with hotkey, and use buttons for the rest. Does it work without hotkey?


![Capture](https://github.com/CraftySalamander/RTS_Overlay/assets/167484039/1d346b75-714a-44ac-9ab9-3b1a107b292a)
![Capture2](https://github.com/CraftySalamander/RTS_Overlay/assets/167484039/45c31f07-63c9-4b6e-b29e-5e2f58045c3f)

**Comment by CraftySalamander** [comment]
The hourglass button does not appear when designing a new BO (see [here](https://youtu.be/qFBkpTnRzWQ?t=538)).
You must close the BO design window and select your BO (see [here](https://youtu.be/qFBkpTnRzWQ?t=747)). The hourglass only appears when selecting a BO with valid timing.

You can also check the settings file (configure hotkeys > Open settings folder).
Check that you have `"timer_available": true,`

**Comment by CraftySalamander** [comment]
Closing the issue since there was no update for the last month.
