### ISSUE TITLE
Version 1.5.3 massive Maleware detection

### ISSUE THREAD

**Issue by Fabibassi** [CraftySalamander/RTS_Overlay#24]
hey there,
i used AOE_Overlay Version 1.5.3 in October 2023 when playing AOE2.
This morning i started my AV Eset with DeepScan because i had an Sus file detection.
After i have come back from work i was suprised with following result:

https://www.virustotal.com/gui/file/2848ec3686847ce3cc8d1c1d23772614b7ad949ee81b83ed437e423149f02dd8?nocache=1

please tell me, this is just getting detected because the Overlay trys to detect time & etc on the screen and not that you used someone else´s detection code which was compromised

**Comment by CraftySalamander** [comment]
Hi.
Since the end of last year, many antivirus softwares started to send false positives, despite the fact that libraries did not evolve.
A similar tool (using the same libraries) is providing the same result (see [here](https://github.com/FluffyMaguro/AoE4_Overlay/issues/31)).

There is no screen analysis and the whole code is mine, except [these common libraries](https://github.com/CraftySalamander/RTS_Overlay/blob/master/requirements.txt).

For more information about this, check [this video](https://youtu.be/qFBkpTnRzWQ). It explains how the time is obtained (basically, the user has to start it manually).
[At the end](https://www.youtube.com/watch?v=qFBkpTnRzWQ&t=1059s), I explain that there are more and more antivirus false positives.
As explained in the video, you can use the [python installation](https://github.com/CraftySalamander/RTS_Overlay?tab=readme-ov-file#python-configuration) (which allows you to check the full code) or wait for the new web-based implementation (I started it this week, specifically to solve these antivirus issues).

**Comment by Fabibassi** [comment]
thanks for the quick response. I thought that this would be the case but had to make sure since im using this system for everything in my life ;)
