### ISSUE TITLE
build order guide is down?

### ISSUE THREAD

**Issue by AumJavalgikar** [CraftySalamander/RTS_Overlay#26]
Hi, sry if this is not the right place to ask, https://buildorderguide.com/ could not be found, is the site down? are there any other ways to get community build orders for aoe2 for the overlay program?

**Comment by CraftySalamander** [comment]
Hi.
Unfortunately, I had no contact with the buildorderguide website creator since the time I added this functionality (more than 1 year ago).
You can ask your question here for buildorderguide: https://github.com/bergerjohannes/buildorderguide/issues

For AoE2, this is the only website with direct exports to RTS Overlay.
Morley Games also has many interesting AoE2 BOs for RTS Overlay format. You can check [his YouTube channel](https://www.youtube.com/@MorleyGames1).

With the latest feature from RTS Overlay, it is now way easier to write your own BO (potentially by adapting another BO found on the web). See demo [here](https://youtu.be/qFBkpTnRzWQ).

**Comment by CraftySalamander** [comment]
I just saw this message on the buildorderguide discord.
-------------------
Sorry for the ping, but as some have noticed that the main site is still down , working on some improvements that have taken longer than expected. So for now, you can access by going to https://build-order-guide.web.app/ . The site will be back up in a few days, expecting some new features to come in the following weeks. It's been a rough time but doing the best to keep a good site up and running. Sorry for the inconvinience

**Comment by CraftySalamander** [comment]
https://buildorderguide.com/ seems to be back.

**Comment by AumJavalgikar** [comment]
Thanks for the follow up ☺️
