### ISSUE TITLE
The Byzantine seem to be missing some icons.  Specifically it seems their mercenary house icons- western mercenary contract and silk road contract are not appearing as icons(at least to me)

### ISSUE THREAD

**Issue by CrazedSadeyr** [CraftySalamander/RTS_Overlay#32]
I've been grabbing a few overlays for the Byzantine and I noticed that when they mention the mercenary contracts it appears as .png stuff rather than the imagine itself, and when I went in to see if i could fix it, I can't seem to find the mercenary contracts as icons in their tech.

**Comment by CrazedSadeyr** [comment]
Also noticed their special version of longbowmen and I assume others are probably missing, too.

**Comment by CraftySalamander** [comment]
Thank you for the report.
The images for AoE4 were not updated since the last game updates.

I added the missing images in [this commit](https://github.com/CraftySalamander/RTS_Overlay/commit/e3c68aa806fb8c618ebef1377e6bc77ac70d39f1).

It will be part of the next release, but you can already download the files [here](https://github.com/CraftySalamander/RTS_Overlay/tree/aom/docs/assets/aoe4) and replace them in your local `aoe4` image folder.

**Comment by CrazedSadeyr** [comment]
Ooh, thank you! ^ ^
