### ISSUE TITLE
[Feature request] Audio reminders and unit counters

### ISSUE THREAD

**Issue by Gvanderl** [CraftySalamander/RTS_Overlay#6]
Hello,

I've been experimenting with my local version of the overlay and I'd like to gage interest for a couple of features. I've worked on those features on my local branches but they're still pretty messy. If you're interested, I could clean it up and create a pull request.
My friends and I aren't that good at the game, so these features are aimed players like us.

First is a simple audio reminder to create villagers. My implementation plays an audio file (placed in the "audio" folder) every time you should create a villager on a loop. This can be disabled or enabled at any moment using a checkbox. It is very useful as low and mid elo players in aoe2 often forget to make villagers, which puts you far behind. 

Second is a unit counter search bar. I haven't done the overlay implementation yet and I'm open to ideas on how to do it properly without making the interface bulky. I have however created a scraper whitch fetches all the counters for all the units (as strings for now). This would be useful as it isn't obvious which unit counters which in aoe2 and it can allow you to check without needing to alt tab and then google it.

Please let me know what you think,
Best regards.

**Comment by CraftySalamander** [comment]
Hello,
It is nice to see you continue working on features.

However, I would prefer not to integrate these ones.
The reason is that there were already people (on reddit) that wondered if this kind of tools were cheating.
Usually, these comments were pretty downvoted because the build order overlay does not provide more features than a BO website on a second screen or post-its with BO glued to the screen (so, case closed).
However, adding a reminder to make villagers could be seen as a grey zone open to discussion (I do not consider it as cheating but some people might see it differently).
Therefore, I prefer to keep it out of my version.

There is however no issue for you to have this feature available in your fork, and for your friends to use your version.
Small tip: try to keep your modifications as much as possible in separate functions/files, so that you could easily merge new features from my overlay in yours in the future (if you want).

For ideas about the unit counter search bars:
- Do it in a new panel (config, BO, match data, counter search)
- Copy the fuzzy search algorithm you are already familiar with
- Make a dictionary where each key is the word to search and its value is a list of strings giving you the information you are looking for.
- Use the result of the fuzzy search to look for the best key, and display its value in your new panel, using 'MultiQLabelDisplay' (like what is done for the BO panel).

Here is what this dictionary could look like (from https://ageofempires.fandom.com/wiki/Genoese_Crossbowman)
units_info = {
'Genoese Crossbowman': [
'It is a foot archer unit with an attack bonus against cavalry.',
'+5, +7 (Elite) vs Cavalry',
'+5, +7 (Elite) vs War elephant',
'+4, +6 (Elite) vs Camel',
'+4, +5 (Elite) vs Ship',
'+4, +5 (Elite) vs Fishing Ship']
}

Of course, these are only suggestions, you do how you want in your overlay version.

**Comment by Gvanderl** [comment]
Yes I understand those features go a bit beyond what was intented in the overlay.
Thanks for the feedback and implementation tips, I'll see what I can do on my branch.
